# Generated by Django 6.0.5 on 2026-05-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='papel',
            field=models.CharField(choices=[('SUPERADMIN', 'Administrador'), ('GESTOR', 'Gestor de Filial'), ('OPERADOR', 'Operador de Caixa'), ('CONTABILISTA', 'Contabilista')], default='OPERADOR', max_length=20),
        ),
    ]
