# Generated by Django 6.0.5 on 2026-05-13 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0002_alter_funcionario_papel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='empresa',
            name='moeda_padrao',
            field=models.CharField(default='AOA', max_length=3),
        ),
        migrations.AddField(
            model_name='empresa',
            name='regime_tributario',
            field=models.CharField(choices=[('GERAL', 'Regime Geral'), ('SIMPLIFICADO', 'Regime Simplificado'), ('EXCLUSAO', 'Regime de Exclusão')], default='GERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='filial',
            name='serie_documentos',
            field=models.CharField(default='A', help_text='Série de faturação (ex: A, B, 2026A)', max_length=10),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='empresa', to='organizacao.endereco'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telemovel',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='filial',
            unique_together={('empresa', 'codigo_agt')},
        ),
    ]
