# Generated by Django 6.0.5 on 2026-05-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0003_alter_empresa_options_alter_endereco_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='papel',
            field=models.CharField(choices=[('SUPERADMIN', 'Administrador'), ('ADMIN', 'Administrador de Filial'), ('GESTOR', 'Gestor de Filial'), ('OPERADOR', 'Operador de Caixa'), ('CONTABILISTA', 'Contabilista')], default='OPERADOR', max_length=20),
        ),
    ]
