# Generated by Django 6.0.5 on 2026-05-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0004_alter_funcionario_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se a filial está ativa'),
        ),
        migrations.AlterField(
            model_name='filial',
            name='serie_documentos',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
