# Generated by Django 6.0.5 on 2026-06-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0005_filial_ativo_alter_filial_serie_documentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
