# Generated by Django 6.0.5 on 2026-05-13 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacao', '0003_alter_empresa_options_alter_endereco_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxaIva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descricao', models.CharField(max_length=100)),
                ('motivo_isencao', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_isencao_agt', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Taxa de IVA',
                'verbose_name_plural': 'Taxas de IVA',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('sigla', models.CharField(max_length=5, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('P', 'Produto'), ('S', 'Serviço')], default='P', max_length=1)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=12)),
                ('codigo_barras', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('ref_interna', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='faturacao.categoria')),
                ('taxa_iva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faturacao.taxaiva')),
                ('unidade_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faturacao.unidademedida')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantidade', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=5.0, max_digits=12)),
                ('corredor', models.CharField(blank=True, max_length=50, null=True)),
                ('prateleira', models.CharField(blank=True, max_length=50, null=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='organizacao.filial')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='faturacao.produto')),
            ],
            options={
                'verbose_name': 'Stock por Filial',
                'verbose_name_plural': 'Stocks por Filial',
                'unique_together': {('produto', 'filial')},
            },
        ),
    ]
