# Generated by Django 6.0.5 on 2026-05-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturacao', '0002_alter_produto_options_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='produtos/thumbs/%Y/%m/'),
        ),
    ]
