# Generated by Django 6.0.5 on 2026-05-18 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturacao', '0003_produto_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('E', 'Entrada (Compra/Ajuste Positivo)'), ('S', 'Saída (Venda/Quebra/Ajuste Negativo)')], max_length=1)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('origem_destino', models.CharField(help_text='Ex: FT-2026/001 (Venda), Entrada de Fornecedor, Ajuste de Inventário', max_length=255)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_stock', to=settings.AUTH_USER_MODEL)),
                ('stock_filial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='faturacao.stock')),
            ],
            options={
                'verbose_name': 'Movimentação de Stock',
                'verbose_name_plural': 'Movimentações de Stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
