# Generated by Django 6.0.5 on 2026-05-20 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_pais_remove_cliente_provincia_and_more'),
        ('faturacao', '0004_movimentacaostock'),
        ('organizacao', '0005_filial_ativo_alter_filial_serie_documentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('FACTURA', 'Factura'), ('PRO_FORMA', 'Pro-Forma'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito'), ('RECIBO', 'Recibo')], max_length=20)),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EMITIDA', 'Emitida'), ('PARCIALMENTE_PAGA', 'Parcialmente Paga'), ('PAGA', 'Paga'), ('ANULADA', 'Anulada'), ('VENCIDA', 'Vencida')], default='RASCUNHO', max_length=20)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_pago', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='clientes.cliente')),
                ('documento_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_relacionados', to='faturacao.documento')),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='organizacao.filial')),
            ],
            options={
                'verbose_name': 'Documento Fiscal',
                'verbose_name_plural': 'Documentos Fiscais',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='LinhaDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(max_length=255)),
                ('codigo_barras', models.CharField(blank=True, max_length=13, null=True)),
                ('quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desconto_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxa_iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='faturacao.documento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linhas_documento', to='faturacao.produto')),
            ],
            options={
                'verbose_name': 'Linha de Documento',
                'verbose_name_plural': 'Linhas de Documento',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('metodo', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('MULTICAIXA', 'Multicaixa'), ('TRANSFERENCIA', 'Transferência Bancária'), ('CHEQUE', 'Cheque'), ('OUTRO', 'Outro')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='faturacao.documento')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_registados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='SerieDocumento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('FACTURA', 'Factura'), ('PRO_FORMA', 'Pro-Forma'), ('NOTA_CREDITO', 'Nota de Crédito'), ('NOTA_DEBITO', 'Nota de Débito'), ('RECIBO', 'Recibo')], max_length=20)),
                ('prefixo', models.CharField(help_text='Ex: FAT, PRO, NC, ND, REC', max_length=10)),
                ('numero_atual', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='organizacao.filial')),
            ],
            options={
                'verbose_name': 'Série de Documento',
                'verbose_name_plural': 'Séries de Documentos',
                'unique_together': {('filial', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='faturacao.seriedocumento'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['filial', 'estado'], name='faturacao_d_filial__677ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['cliente'], name='faturacao_d_cliente_d6c072_idx'),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['numero'], name='faturacao_d_numero_39ab21_idx'),
        ),
    ]
