# Generated by Django 6.0.5 on 2026-05-26 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturacao', '0005_documento_linhadocumento_pagamento_seriedocumento_and_more'),
        ('organizacao', '0005_filial_ativo_alter_filial_serie_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200)),
                ('nif', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='organizacao.filial')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='faturacao.fornecedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.CreateModel(
            name='LinhaCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='faturacao.compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='faturacao.produto')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
