# Generated by Django 6.0.5 on 2026-05-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_token_jti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
