# Generated by Django 6.0.5 on 2026-05-18 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tipo', models.CharField(choices=[('P', 'Particular (Pessoa Singular)'), ('E', 'Empresa (Organização/Pessoa Coletiva)')], default='P', max_length=1)),
                ('nome', models.CharField(max_length=255)),
                ('nif', models.CharField(help_text='NIF do Cliente (9 dígitos para empresas)', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('provincia', models.CharField(blank=True, default='Luanda', max_length=50, null=True)),
                ('pais', models.CharField(default='Angola', max_length=50)),
                ('razao_social', models.CharField(blank=True, help_text='Designação Social jurídica', max_length=255, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('bilhete_identidade', models.CharField(blank=True, help_text='BI se for diferente do NIF', max_length=15, null=True, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
    ]
